---
deployment:
  tasks:
    - export REPOPATH=/home/timetowe/repositories/nao/*
    - export SITEPATH=/home/timetowe/public_html/nao.time-to-web.com
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH